updated netpipe run scripts

diff --git a/files/netpipeapp/run b/files/netpipeapp/run
--- a/files/netpipeapp/run
+++ b/files/netpipeapp/run
@@ -1,16 +1,17 @@
-# Add commands that form the body of your experiment here
 set -x
 
 INSMOD=insmod
 RMMOD=rmmod
 ETHTOOL=/app/ethtool-4.5/ethtool
 SETAFFINITY=/app/perf/set_irq_affinity_ixgbe.sh
+DISABLE_HT=/app/perf/disable_ht.sh
 IP=ip
 TASKSET=taskset
 DMESG=dmesg
 CAT=cat
 SLEEP=sleep
-NETPIPE=/app/NetPIPE-3.7.1/NPtcp_static
+NETPIPE=/app/NetPIPE-3.7.1/NPtcp_joules
+RAPL_POW_MOD=/app/uarch-configure/rapl-read/rapl-power-mod
 ETHMODULE_ORIG=/app/ixgbe/ixgbe_orig.ko
 ETHMODULE_WITHLOG=/app/ixgbe/ixgbe_log.ko
 
@@ -18,15 +19,16 @@ NETCLASS="/24"
 
 ROLE="${1}"
 DEVICE="${2}"
-MYIP="${3}"
-LOG="${4}"
+LOG="${3}"
+MSGSIZES="${4}"
+
 ITRS="${5}"
-MSGSIZES="${6}"
-REPEAT="${7}"
-ITERS="${8}"
-TASKSETCPU="${9}"
-CTLFILE="${10}"
-PERTURBATION="${11}"
+MDVFS="${6}"
+MRAPL="${7}"
+
+REPEAT="${8}"
+ITERS="${9}"
+TASKSETCPU="${10}"
 
 SERVER=${ROLE##*:}
 if [[ $ROLE == $SERVER ]]; then
@@ -38,14 +40,15 @@ fi
 
 DEVICE=${DEVICE:-"eth0"}
 MYIP=${MYIP:-"192.168.1.9"}
-ITRS=${ITRS:-"100 200 12"}
-MSGSIZES=${MSGSIZES:-"64,64 1024,1024 8192,8192 64,8192"}
+#ITRS=${ITRS:-"0 4 8 12 16 20 24 28 32 36 40 60 80 100"}
+ITRS=${ITRS:-"1"}
+#MSGSIZES=${MSGSIZES:-"64 128 256 512 1024 2048 3072 4096 8192 12288 16384 24576 49152 65536 98304 131072 196608 262144 393216 524288 786432"}
+MSGSIZES=${MSGSIZES:-"64 8192 65536 524288"}
 ITERS=${ITERS:-"5000"}
 TASKSETCPU=${TASKSETCPU:-"1"}
-CTLFILE=${CTLFILE:-"192.168.1.1:netpipeserver"}
-CTLFILE="${CTLFILE}.${MYIP}.output"
-PERTURBATION=${PERTURBATION:-"0"}
-REPEAT=${REPEAT:-100}
+REPEAT=${REPEAT:-10}
+MDVFS=${MDVFS:="0x1d00 0x1c00 0x1b00 0x1a00 0x1900 0x1800 0x1700 0x1600 0x1500 0x1400 0x1300 0x1200 0x1100 0x1000 0xf00 0xe00 0xd00 0xc00"}
+MRAPL=${MRAPL:-"135"}
 
 if [[ ${LOG} == "NOLOG" ]]; then
     ETHMODULE=${ETHMODULE_ORIG}
@@ -53,64 +56,70 @@ else
     ETHMODULE=${ETHMODULE_WITHLOG}
 fi
 
+${INSMOD} ${ETHMODULE}
+${IP} addr add ${APP_MYIP} dev ${DEVICE}
+ip link set ${DEVICE} up
+${SLEEP} 1
+
 function configDevice()
 {
-   itr=$1
+    itr=$1
+    
+    # set itr to be X
+    ${ETHTOOL} -C ${DEVICE} rx-usecs $itr
+    ${IP} link set ${DEVICE} down
+    ${IP} link set ${DEVICE} up
 
-     ${IP} link set eth0 down
-     ${RMMOD} ixgbe
-
-   # initializes ixgbe device driver with no logging
-     ${INSMOD} ${ETHMODULE}
-
-   #set ip:  
-     ${IP} addr flush $DEVICE
-   # make X configurable
-     ${IP} addr add ${MYIP}${NETCLASS} dev $DEVICE
-     ${IP} link set $DEVICE up
-
-   # set itr to be X - should make this parameter also configurable
-     ${ETHTOOL} -C ${DEVICE} rx-usecs $itr
-     ${IP} link set ${DEVICE} down
-     ${IP} link set ${DEVICE} up
-
-   # pin receive queues to cores
+    # paranoia
+    sleep 1    
+    # pin receive queues to cores again
     ${SETAFFINITY} -x all ${DEVICE}
+
+    #itr=$1
+    #${ETHTOOL} -C ${DEVICE} rx-usecs ${itr}
+    #${SLEEP} 1
 }
 
-
-
-for itr in $ITRS; do
-
-    configDevice $itr
-    
-    # run netpipe for a fixed message size
-    for p in $PERTURBATION; do
-	for iters in $ITERS; do
-	    for msgSize in $MSGSIZES; do
-    		lmsg=${msgSize%%,*}
-		umsg=${msgSize##*,}
-		for ((i=0;i<$REPEAT; i++)); do
+for ((i=0;i<$REPEAT; i++)); do
+    for msg in $MSGSIZES; do
+    	for itr in $ITRS; do
+    	    configDevice $itr
+	    for dvfs in ${MDVFS}; do
+	    	if [[ ${ROLE} == "SERVER" ]]; then
+		   wrmsr -p ${TASKSETCPU} 0x199 ${dvfs}
+		fi
+	    	${SLEEP} 1  	
+	    	for r in ${MRAPL}; do
 		    if [[ ${ROLE} == "SERVER" ]]; then
-			echo "$ROLE:$MYIP: RUN:$i ${TASKSET} -c ${TASKSETCPU} ${NETPIPE}  -l ${lmsg} -u ${umsg} -n ${iters} -p ${p} -r -I"
-			 ${TASKSET} -c ${TASKSETCPU} ${NETPIPE}  -l ${lmsg} -u ${umsg} -n ${iters} -p ${p} -r -I
+		       ${RAPL_POW_MOD} ${r}
+		       ${SLEEP} 1
+		    fi
+		    if [[ ${ROLE} == "SERVER" ]]; then
+			## clean up some previous entries just incase
+		        ${ETHTOOL} -C ${DEVICE} DUMP_DYNAMIC_ITR $((TASKSETCPU+1))
+		        ${DMESG} -C
+			
+#			echo "$ROLE:$MYIP: RUN:$i ${TASKSET} -c ${TASKSETCPU} ${NETPIPE}  -l ${msg} -u ${msg} -n ${ITERS} -p 0 -r -I &> /app/np.server.${i}_${msg}_${ITERS}_${itr}_${dvfs}_${r}"	
+			${TASKSET} -c ${TASKSETCPU} ${NETPIPE} -l ${msg} -u ${msg} -n ${ITERS} -p 0 -r -I &> /app/np.server.${i}_${msg}_${ITERS}_${itr}_${dvfs}_${r}
 			# dumps logs to dmesg
 			if [[ ${ETHMODULE} == ${ETHMODULE_WITHLOG} ]]; then
 			     ${ETHTOOL} -C ${DEVICE} DUMP_DYNAMIC_ITR $((TASKSETCPU+1))
-			     ${DMESG} 
-			     ${DMESG} -c &>  /app/dmesg_devicelog.${itr}_${i}_${msgSize}_${iters}_${p}
+			     ${DMESG} -c &>  /app/dmesg_devicelog.${i}_${msg}_${ITERS}_${itr}_${dvfs}_${r}
 			fi
+			${SLEEP} 5
 		    else
-			echo "$MYIP: $ROLE:$SERVER RUN:$i ${TASKSET} -c ${TASKSETCPU} ${NETPIPE} -h ${SERVER} -l ${lmsg} -u ${umsg} -n ${iters} -p ${p} -r -I"
-			while ! ${TASKSET} -c ${TASKSETCPU} ${NETPIPE} -h ${SERVER} -l ${lmsg} -u ${umsg} -n ${iters} -p ${p} -r -I; do
+#			echo "$MYIP: $ROLE:$SERVER RUN:$i ${TASKSET} -c ${TASKSETCPU} ${NETPIPE} -h ${SERVER} -l ${msg} -u ${msg} -n ${ITERS} -p 0 -r -I > /app/np.out.${i}_${msg}_${ITERS}_${itr}_${dvfs}_${r}"
+			while ! ${TASKSET} -c ${TASKSETCPU} ${NETPIPE} -h ${SERVER} -l ${msg} -u ${msg} -n ${ITERS} -p 0 -r -I; do
 			    echo "FAILED: Server not ready trying again ..."
-			    ${SLEEP} 10
+			    ${SLEEP} 5
 			done
-			 ${CAT} np.out
-			 ${CAT} np.out > /app/np.out.${itr}_${i}_${msgSize}_${iters}_${p}
+			${CAT} np.out > /app/np.out.${i}_${msg}_${ITERS}_${itr}_${dvfs}_${r}
+			${SLEEP} 5
 		    fi
-		done
-	    done
-	done
+		    scp /app/*.${i}_${msg}_${ITERS}_${itr}_${dvfs}_${r} 192.168.1.153:/root/Appliances/npApp/results/
+		    #scp np.out 192.168.1.153:/root/Appliances/npApp/results/np.client.${i}_${itr}_${msg}_${dvfs}_${r}
+	    	done
+            done
+        done	
     done
 done
